#!/usr/bin/env bash

# Local check that we are likely to pass CI
# CI is quite slow so it's nice to be able to run locally

set -o errexit
set -o xtrace

# ensure rustfmt has been run
cargo fmt --all -- --check
# ensure we don't have broken links in docs
cargo doc --all-features --document-private-items

# ensure we at least compile without default features
cargo check --manifest-path=font-types/Cargo.toml --no-default-features
cargo check --manifest-path=read-fonts/Cargo.toml --no-default-features

cargo clippy --all-features --all-targets -- -D warnings

cargo test --all-features
cargo test --no-default-features
